{{- $fullName := include "mychart.fullname" . -}}
{{- $svcPort := .Values.service.port -}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: doggramm.com
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}